routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::prefix('admin')->group(function(){

Route::resource('customer', 'CustomerController');
Route::get('customer/delete/{id}', 'CustomerController@delete_data')->name('customer.delete_data');
Route::post('customer/status', 'CustomerController@status')->name('customer.status');
Route::post('customer/search', 'CustomerController@search' )->name('customer.search');


Route::resource('employee', 'EmployeeController');
Route::get('employee/delete/{id}', 'EmployeeController@delete_data')->name('employee.delete_data');
Route::post('employee/status', 'EmployeeController@status')->name('employee.status');

Route::resource('admin', 'AdminController');
Route::get('admin/delete/{id}', 'CustomerController@delete_data')->name('admin.delete_data');
Route::post('admin/status', 'CustomerController@status')->name('admin.status');



Route::resource('/home_slider', 'HomeSliderController');
Route::get('home_slider/delete/{id}', 'HomeSliderController@delete_data')->name('home_slider.delete_data');
Route::post('home_slider/status', 'HomeSliderController@status')->name('home_slider.status');
Route::post('home_slider/search', 'HomeSliderController@search' )->name('home_slider.search');

Route::resource('post', 'PostController');
Route::get('post/delete/{id}', 'PostController@delete_data')->name('post.delete_data');
Route::post('post/status', 'PostController@status')->name('post.status');
Route::post('post/search', 'PostController@search' )->name('post.search');

Route::resource('sub_cat', 'SubCategoryController');
Route::get('sub_cat/delete/{id}', 'SubCategoryController@delete_data')->name('sub_cat.delete_data');
Route::post('sub_cat/status', 'SubCategoryController@status')->name('sub_cat.status');
Route::post('sub_cat/search', 'SubCategoryController@search' )->name('sub_cat.search');


Route::resource('country', 'CountryController');
Route::get('country/delete/{id}', 'CountryController@delete_data')->name('country.delete_data');
Route::post('country/status', 'CountryController@status')->name('country.status');
// Route::post('country/search', 'CountryController@search' )->name('country.search');


Route::resource('city', 'CityController');
Route::get('city/delete/{id}', 'CityController@delete_data')->name('city.delete_data');
Route::post('city/status', 'CityController@status')->name('city.status');
Route::post('city/search', 'CityController@search' )->name('city.search');

});



Route::resource('/home','HomeController');
Route::get('home/slider-detail/{slug}','HomeController@slider_detail')->name('home_slider_detail');
Route::get('home/post-detail/{slug}','HomeController@post_detail')->name('home_post_detail');


Route::resource('/contact', 'ContactController');


Route::resource('/single', 'SingleController');


Route::resource('/error', 'ErrorController');


Route::resource('/about_us', 'About_usController');




Route::resource('category', 'CategoryController');
Route::post('category/status', 'CategoryController@status')->name('category.status');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/users/theme/default.blade.php
<!DOCTYPE html>
<html>
<head>
  <title>magExpress</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{{asset('user/assets/css/bootstrap.min.css')}}">
  <link rel="stylesheet" type="text/css" href="{{asset('user/assets/css/font-awesome.min.css')}}">
  <link rel="stylesheet" type="text/css" href="{{asset('user/assets/css/animate.css')}}">
  <link rel="stylesheet" type="text/css" href="{{asset('user/assets/css/slick.css')}}">
  <link rel="stylesheet" type="text/css" href="{{asset('user/assets/css/theme.css')}}">
  <link rel="stylesheet" type="text/css" href="{{asset('user/assets/css/style.css')}}">
<!--[if lt IE 9]>
<script src="{{asset('user/assets/js/html5shiv.min.js')}}"></script>
<script src="{{asset('user/assets/js/respond.min.js')}}"></script>
<![endif]-->
</head>
<body>
  <div id="preloader">
    <div id="status">&nbsp;</div>
  </div>
  <a class="scrollToTop" href="#"><i class="fa fa-angle-up"></i></a>
  <div class="container">
    @section('header')
    @include('users.theme.header')
    @show
    
    @section('navbar')
    @include('users.theme.navbar')
    @show

    @yield('content')


    <footer id="footer">
     @section('footer')
     @include('users.theme.footer')
     @show
   </footer>
   <script src="{{asset('user/assets/js/jquery.min.js')}}"></script> 
   <script src="{{asset('user/assets/js/bootstrap.min.js')}}"></script> 
   <script src="{{asset('user/assets/js/wow.min.js')}}"></script> 
   <script src="{{asset('user/assets/js/slick.min.js')}}"></script> 
   <script src="{{asset('user/assets/js/custom.js')}}"></script>
 </body>
 </html>

resources/views/users/theme/footer.blade.php
<div class="footer_top">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4">
          <div class="single_footer_top wow fadeInLeft">
            <h2>Flicker Images</h2>
            <ul class="flicker_nav">
              <li><a href="#"><img src="{{asset('user/images/75x75.jpg')}}" alt=""></a></li>
              <li><a href="#"><img src="{{asset('user/images/75x75.jpg')}}" alt=""></a></li>
              <li><a href="#"><img src="{{asset('user/images/75x75.jpg')}}" alt=""></a></li>
              <li><a href="#"><img src="{{asset('user/images/75x75.jpg')}}" alt=""></a></li>
              <li><a href="#"><img src="{{asset('user/images/75x75.jpg')}}" alt=""></a></li>
              <li><a href="#"><img src="{{asset('user/images/75x75.jpg')}}" alt=""></a></li>
              <li><a href="#"><img src="{{asset('user/images/75x75.jpg')}}" alt=""></a></li>
              <li><a href="#"><img src="{{asset('user/images/75x75.jpg')}}" alt=""></a></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4">
          <div class="single_footer_top wow fadeInDown">
            <h2>Labels</h2>
            <ul class="labels_nav">
              <li><a href="#">Gallery</a></li>
              <li><a href="#">Business</a></li>
              <li><a href="#">Games</a></li>
              <li><a href="#">Fashion</a></li>
              <li><a href="#">Sports</a></li>
              <li><a href="#">Technology</a></li>
              <li><a href="#">Slider</a></li>
              <li><a href="#">Life &amp; Style</a></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4">
          <div class="single_footer_top wow fadeInRight">
            <h2>About Us</h2>
            <p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed nec laoreet orci, eget ullamcorper quam. Phasellus lorem neque, </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="footer_bottom">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
          <div class="footer_bottom_left">
            <p>Copyright &copy; 2045 <a href="index.html">magExpress</a></p>
          </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
          <div class="footer_bottom_right">
            <p>Developed BY Wpfreeware</p>
          </div>
        </div>
      </div>
    </div>
  </div>

resources/views/users/theme/header.blade.php
<header id="header">
    <div class="row">
      <div class="col-lg-12 col-md-12">
        <div class="header_top">
          <div class="header_top_left">
            <ul class="top_nav">
              <li><a href="index.html">Home</a></li>
              <li><a href="pages/page.html">About</a></li>
              <li><a href="pages/contact.html">Contact</a></li>
              <li><a href="pages/404.html">Error Page</a></li>
            </ul>
          </div>
          <div class="header_top_right">
            <form action="#" class="search_form">
              <input type="text" placeholder="Text to Search">
              <input type="submit" value="">
            </form>
          </div>
        </div>
        <div class="header_bottom">
          <div class="header_bottom_left"><a class="logo" href="index.html">mag<strong>Express</strong> <span>A Pro Magazine Template</span></a></div>
          <div class="header_bottom_right"><a href="#"><!-- <img src="{{asset('user/images/addbanner_728x90_V1.jpg')}}" alt=""> --></a></div>
        </div>
      </div>
    </div>
  </header>

resources/views/users/theme/navbar.blade.php
<div id="navarea">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav custom_nav">
            <li class=""><a href="{{route('home.index')}}">Home</a></li>
            <li class="dropdown"> <a href="#" class="" data-toggle="dropdown" role="button" aria-expanded="false">Archives</a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="pages/archive-main.html">Archive</a></li>
                <li><a href="pages/archive1.html">Archive 1</a></li>
                <li><a href="pages/archive2.html">Archive 2</a></li>
                <li><a href="pages/archive3.html">Archive 3</a></li>
              </ul>
            </li>
            <li><a href="{{route('single.index')}}">Single page</a></li>
            <li><a href="{{route('contact.index')}}">Contact</a></li>
            <li><a href="{{route('error.index')}}">404 page</a></li>
          </ul>
        </div>
      </div>
    </nav>
  </div>