routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::prefix('admin')->group(function(){

Route::resource('customer', 'CustomerController');
Route::get('customer/delete/{id}', 'CustomerController@delete_data')->name('customer.delete_data');
Route::post('customer/status', 'CustomerController@status')->name('customer.status');
Route::post('customer/search', 'CustomerController@search' )->name('customer.search');


Route::resource('employee', 'EmployeeController');
Route::get('employee/delete/{id}', 'EmployeeController@delete_data')->name('employee.delete_data');
Route::post('employee/status', 'EmployeeController@status')->name('employee.status');

Route::resource('admin', 'AdminController');
Route::get('admin/delete/{id}', 'CustomerController@delete_data')->name('admin.delete_data');
Route::post('admin/status', 'CustomerController@status')->name('admin.status');



Route::resource('/home_slider', 'HomeSliderController');
Route::get('home_slider/delete/{id}', 'HomeSliderController@delete_data')->name('home_slider.delete_data');
Route::post('home_slider/status', 'HomeSliderController@status')->name('home_slider.status');
Route::post('home_slider/search', 'HomeSliderController@search' )->name('home_slider.search');

Route::resource('post', 'PostController');
Route::get('post/delete/{id}', 'PostController@delete_data')->name('post.delete_data');
Route::post('post/status', 'PostController@status')->name('post.status');
Route::post('post/search', 'PostController@search' )->name('post.search');

Route::resource('sub_cat', 'SubCategoryController');
Route::get('sub_cat/delete/{id}', 'SubCategoryController@delete_data')->name('sub_cat.delete_data');
Route::post('sub_cat/status', 'SubCategoryController@status')->name('sub_cat.status');
Route::post('sub_cat/search', 'SubCategoryController@search' )->name('sub_cat.search');


Route::resource('country', 'CountryController');
Route::get('country/delete/{id}', 'CountryController@delete_data')->name('country.delete_data');
Route::post('country/status', 'CountryController@status')->name('country.status');
// Route::post('country/search', 'CountryController@search' )->name('country.search');


Route::resource('city', 'CityController');
Route::get('city/delete/{id}', 'CityController@delete_data')->name('city.delete_data');
Route::post('city/status', 'CityController@status')->name('city.status');
Route::post('city/search', 'CityController@search' )->name('city.search');

});



Route::resource('/home','HomeController');
Route::get('home/slider-detail/{slug}','HomeController@slider_detail')->name('home_slider_detail');
Route::get('home/post-detail/{slug}','HomeController@post_detail')->name('home_post_detail');


Route::resource('/contact', 'ContactController');


Route::resource('/single', 'SingleController');


Route::resource('/error', 'ErrorController');


Route::resource('/about_us', 'About_usController');




Route::resource('category', 'CategoryController');
Route::post('category/status', 'CategoryController@status')->name('category.status');

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    protected $guarded = [];

}

app/Http/Controllers/CustomerController.php
<?php



namespace App\Http\Controllers;

use App\Customer;

use Illuminate\Http\Request;

use App\Item;



class CustomerController extends Controller

{

    public function __construct()

    {


    }


    public function index()

    {
        // dd("index");
        $customer = Customer::get();
        return view('customer.index', compact('customer'));

    }

    public function create()

    {
        return view('customer.add');
    }

    public function store(Request $request)
    {
        request()->validate([

            'fname' => 'required',
            'lname' => 'required',
            'email' => 'required', 
            'mobile' => 'required', 
            'picture' => 'required' 
        ]);
        // dd($request->all());
        if($request->hasFile('picture'))
        {
            $image = $request->file('picture');
            $name = time().".".$image->getClientOriginalExtension();
            $destinationPath = public_path('/images');
            $image->move($destinationPath,$name);
            $image_add=$name;
        }else
        {
            $image_add="default.png";
        }
        $data = array(
            "fname" => request('fname'),
            "lname" => $request->lname,
            "email" => $request->email,
            "mobile" => $request->mobile,
            "picture"=> $image_add,
        );


        $save = Customer::insert($data);
        if($save)
        {
            return redirect(route('customer.index'));
        }
        
    }

    public function show()

    {


    }

    public function edit($id)

    {
        $data = Customer::find($id);
        // dd($data);
        return view('customer.update',compact('data'));
    }

    public function update(Request $request,$id)
    {
        // dd($request->all());
        $check = Customer::find($id);   

        if($check)
        {
            if($request->hasFile('picture'))
            {
                $image = $request->file('picture');
                $name = time().".".$image->getClientOriginalExtension();
                $destinationPath = public_path('/images');
                $image->move($destinationPath,$name);
                $data['picture']=$name;
            }
            $data["fname"] = request('fname');
            $data["lname"] = request('lname');
            $data["email"] = request('email');
            $data["mobile"] = request('mobile');
    
            $updated = Customer::whereId($id)->update($data);
            if($updated)
            {
                return redirect(route('customer.index'));       
            }   
        }
    }

    public function destroy()
    {


    }

    public function delete_data($id)
    {
        $check = Customer::find($id); 
        if($check)
        {
             Customer::whereId($id)->delete();
             return redirect(route('customer.index'));   
        }else
        {
            dd("not delete");   
        }

    }
     public function status(Request $request)
    {
        // dd($request->all());
        $id = request('id');    
       
        if (request('status')==1) {
             $data["status"] = 0;
        }else{
            $data["status"] = 1;
        }

        $updated = Customer::whereId($id)->update($data);
          if($updated)
            {
                return redirect(route('customer.index'));       
            }   

    }

    public function search(Request $request)
    {
        $search =$request->search;
        $customer = Customer::where('fname', 'LIKE', "%$search%")
        ->orWhere('lname', 'LIKE', "%$search%")
        ->orWhere('mobile', 'LIKE', "%$search%")
        ->orWhere('email', 'LIKE', "%$search%")
        ->get();

        // dd($customer);
           
        
        return view('customer.search', compact('customer'));
    }
    

    

    
}

resources/views/customer/add.blade.php
@extends('theme.default')

@section('title', 'Add Customer')


@section('content')


<div class="content-wrapper">
   <!-- Content Header (Page header) -->
   <section class="content-header">
      <div class="header-title">
         <h1>Add Customer</h1>
      </div>
   </section>
   <!-- Main content -->
   <section class="content">

      <div class="row">
         <!-- Form controls -->
         <div class="col-sm-10">
            <div class="panel panel-bd lobidrag">
               <div class="panel-body">

                  <form class="col-sm-8" action="{{route('customer.store')}}" method="POST" enctype="multipart/form-data">

                   @csrf

                   <div class="form-group">
                     <label>First Name</label>
                     <input type="text" name="fname" class="form-control" placeholder="Enter First Name" >
                  </div>
                  <div class="form-group">
                     <label>Last Name</label>
                     <input type="text" name="lname" class="form-control" placeholder="Enter last Name" >
                  </div>
                  <div class="form-group">
                     <label>Email</label>
                     <input type="email" name="email" class="form-control" placeholder="Enter Email" >
                  </div>
                  <div class="form-group">
                     <label>Mobile</label>
                     <input type="number" name="mobile" class="form-control" placeholder="Enter Mobile" >
                  </div>
                  <div class="form-group">
                     <label>Picture upload</label>
                     <input type="file" name="picture" >
                  </div>
                  <div class="reset-button">
                     <input type="submit"  class="btn btn-success" value="Save">
                  </div>
                  <div class="notification is-danger">
                     <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{$error}}</li>
                        @endforeach
                     </ul>
                  </div>
               </form>
            </div>
         </div>
      </div>
   </div>
</section>
<!-- /.content -->
</div>



@endsection

resources/views/customer/index.blade.php
@extends('theme.default')

@section('title', 'Add Customer')


@section('content')

<div class="row">
  <div class="col-md-12">
    <div class="box">
      <div class="box-header with-border">

        <a href="{{route('customer.create')}}" class="btn btn-success">Add Customer</a>
      </div>

      <form action="{{route('customer.search')}}" method="POST">
       @csrf
       <label for="search">Search:</label>
       <input type="text" id="search" name="search">
       <input type="submit" value="Search" class="btn-success">
     </form>
     <!--  <div class="box-header with-border">
       <label for="search">Search:</label>
      <input type="text" id="search" name="search">
      <a href="{{route('customer.search')}}" class="btn btn-success">Search</a>
    </div> -->
    <!-- /.box-header -->


    <div class="box-body">
      <table class="table table-bordered">
        <tbody>
          <tr>
           <th>Sr.No</th>
           <th>First Name</th>
           <th>Last Name</th>
           <th>Mobile No.</th>
           <th>Email</th>
           <th>Image</th>
           <th>Status</th>
           <th>Action</th>
         </tr>

         @if(isset ($customer))

         @foreach ($customer as $value)

         <tr>
           <td>{{$value->id}}</td>
           <td>{{$value->fname}}</td>
           <td>{{$value->lname}}</td>
           <td>{{$value->mobile}}</td>
           <td>{{$value->email}}</td>
           <td><img src="{{asset('images/'.$value->picture)}}" alt="" width="30px"></td>
           <td>
            <form action="{{route('customer.status')}}" method="POST">
             @csrf
             <input type="hidden" name="id" value="{{$value->id}}">
             <input type="hidden" name="status" value="{{$value->status}}">
             @if($value->status == 1)
             <input type="submit" class="btn btn-success" value="Active">
             @else
             <input type="submit" class="btn btn-danger" value="Deactive">
             @endif
           </form>
         </td>
         <td><a href="{{route('customer.edit',$value->id)}}" class="btn btn-success">Edit</a>
          <a href="{{route('customer.delete_data',$value->id)}}" class="btn btn-danger">Delete</a> </td> 
        </tr>

        @endforeach
        @endif
      </tbody>
    </table>
  </div>

  <!-- /.box-body -->

</div>
<!-- /.box -->


</div>
<!-- /.col -->
</div>


@endsection

resources/views/customer/search.blade.php
@extends('theme.default')

@section('title', 'Search')


@section('content')

<div class="row">
  <div class="col-md-12">
    <div class="box">
      <div class="box-header with-border">

        <a href="{{route('customer.create')}}" class="btn btn-success">Add Customer</a>
      </div>

      <form action="{{route('customer.search')}}" method="POST">
       @csrf
       <label for="search">Search:</label>
       <input type="text" id="search" name="search">
       <input type="submit" value="Search" class="btn-success">
     </form>
     <!--  <div class="box-header with-border">
       <label for="search">Search:</label>
      <input type="text" id="search" name="search">
      <a href="{{route('customer.search')}}" class="btn btn-success">Search</a>
    </div> -->
    <!-- /.box-header -->


    <div class="box-body">
      <table class="table table-bordered">
        <tbody>
          <tr>
           <th>Sr.No</th>
           <th>First Name</th>
           <th>Last Name</th>
           <th>Mobile No.</th>
           <th>Email</th>
           <th>Image</th>
           <th>Status</th>
           <th>Action</th>
         </tr>

         @if(isset ($customer))

         @foreach ($customer as $value)

         <tr>
           <td>{{$value->id}}</td>
           <td>{{$value->fname}}</td>
           <td>{{$value->lname}}</td>
           <td>{{$value->mobile}}</td>
           <td>{{$value->email}}</td>
           <td><img src="{{asset('images/'.$value->picture)}}" alt="" width="30px"></td>
           <td>
            <form action="{{route('customer.status')}}" method="POST">
             @csrf
             <input type="hidden" name="id" value="{{$value->id}}">
             <input type="hidden" name="status" value="{{$value->status}}">
             @if($value->status == 1)
             <input type="submit" class="btn btn-success" value="Active">
             @else
             <input type="submit" class="btn btn-danger" value="Deactive">
             @endif
           </form>
         </td>
         <td><a href="{{route('customer.edit',$value->id)}}" class="btn btn-success">Edit</a>
          <a href="{{route('customer.delete_data',$value->id)}}" class="btn btn-danger">Delete</a> </td> 
        </tr>

        @endforeach
        @endif
      </tbody>
    </table>
  </div>

  <!-- /.box-body -->

</div>
<!-- /.box -->


</div>
<!-- /.col -->
</div>


@endsection

resources/views/customer/update.blade.php
@extends('theme.default')

@section('title', 'Add Customer')


@section('content')


<div class="content-wrapper">
   <!-- Content Header (Page header) -->
   <section class="content-header">
      <div class="header-title">
         <h1>Add Customer</h1>
      </div>
   </section>
   <!-- Main content -->
   <section class="content">

      <div class="row">
         <!-- Form controls -->
         <div class="col-sm-10">
            <div class="panel panel-bd lobidrag">
               <div class="panel-body">

                  <form class="col-sm-8" action="{{ route('customer.update',$data->id) }}" method="POST" enctype="multipart/form-data">
                     {!! csrf_field() !!}
                <input name="_method" type="hidden" value="PATCH">

                   <div class="form-group">
                     <label>First Name</label>
                     <input type="text" name="fname" class="form-control" value="@isset($data->fname){{$data->fname}}@endisset" placeholder="Enter First Name" >
                  </div>
                  <div class="form-group">
                     <label>Last Name</label>
                     <input type="text" name="lname" class="form-control" value="@isset($data->lname){{$data->lname}}@endisset" placeholder="Enter last Name" >
                  </div>
                  <div class="form-group">
                     <label>Email</label>
                     <input type="email" name="email" class="form-control" value="@isset($data->email){{$data->email}}@endisset" placeholder="Enter Email" >
                  </div>
                  <div class="form-group">
                     <label>Mobile</label>
                     <input type="number" name="mobile" class="form-control" value="@isset($data->mobile){{$data->mobile}}@endisset" placeholder="Enter Mobile" >
                  </div>
                  <div class="form-group">
                     <img src="{{asset('images/'.$data->picture)}}" alt="" width="30px"><br>
                     <label>Picture upload</label>
                     <input type="file" name="picture">
                  </div>
                  <div class="reset-button">
                     <input type="submit" name="save" id="save" class="btn btn-success" value="Save">
                  </div>
               </form>
            </div>
         </div>
      </div>
   </div>
</section>
<!-- /.content -->
</div>



@endsection